/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// Generates src/assets/generated/licenses.ts — the data behind Settings → About →
// "Open source licenses".
//
// Sources:
//   - the project itself (root LICENSE)
//   - every production dependency, via `pnpm licenses list --prod --json`
//
// Dev dependencies are skipped: they never reach the bundle, so listing them
// would overstate what actually ships.
//
// The output is committed (same convention as src/lib/graphql/generated) and is
// excluded from oxlint/oxfmt — see the ignorePatterns in .oxlintrc.jsonc /
// .oxfmtrc.json. It is regenerated by `pnpm setup`, which both `pnpm dev` and
// `pnpm build` run.
//
// Output must stay deterministic: no timestamps, stable sort order, ids assigned
// in first-seen order. Otherwise every `pnpm setup` would produce a diff.

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

const OUTPUT_FILE = path.resolve(import.meta.dirname, '../../src/assets/generated/licenses.ts');
const PROJECT_LICENSE_FILE = path.resolve(import.meta.dirname, '../../LICENSE');

/** Licenses of the project itself and every production dependency. */
const PROJECT_NAME = 'Suwayomi-WebUI';
const PROJECT_LICENSE = 'MPL-2.0';

type PnpmLicenseEntry = {
    name: string;
    versions: string[];
    /** Absolute paths into the pnpm store. Never written to the output. */
    paths?: string[];
    license?: string;
    author?: string | { name?: string; email?: string; url?: string };
    homepage?: string;
};

/** Matches LICENSE / LICENSE.md / LICENSE-MIT / UNLICENSE / COPYING / COPYING.LESSER … */
const LICENSE_FILE_PATTERN = /^(?:(?:un)?licen[cs]e|copying)\b/i;

type CollectedPackage = {
    name: string;
    version: string;
    license: string;
    author?: string;
    homepage?: string;
    text: string | null;
};

const normalizeAuthor = (author: PnpmLicenseEntry['author']): string | undefined => {
    if (!author) {
        return undefined;
    }

    if (typeof author === 'string') {
        return author.trim() || undefined;
    }

    return author.name?.trim() || author.email?.trim() || undefined;
};

/**
 * `LICENSE` (no extension) outranks `LICENSE.md`/`LICENSE.txt`, which in turn
 * outrank variants like `LICENSE-MIT` — packages that dual-license ship several
 * files, and picking a stable one keeps the output deterministic.
 */
const licenseFileRank = (name: string): number =>
    ['license', 'licence', 'unlicense'].includes(path.basename(name, path.extname(name)).toLowerCase()) ? 0 : 1;

/** Finds the license file shipped inside an installed package, if any. */
const findLicenseFile = (packageDir: string): string | null => {
    let entries: fs.Dirent[];
    try {
        entries = fs.readdirSync(packageDir, { withFileTypes: true });
    } catch {
        return null;
    }

    const candidates = entries
        .filter((entry) => entry.isFile() && LICENSE_FILE_PATTERN.test(entry.name))
        .map((entry) => entry.name);

    if (!candidates.length) {
        return null;
    }

    candidates.sort((a, b) => licenseFileRank(a) - licenseFileRank(b) || a.localeCompare(b));

    return path.join(packageDir, candidates[0]);
};

/** CRLF → LF and drop trailing blank lines: the same text is otherwise stored twice. */
const normalizeText = (text: string): string => `${text.replaceAll('\r\n', '\n').trimEnd()}\n`;

const collectFromPnpm = (): CollectedPackage[] => {
    const raw = execSync('pnpm licenses list --prod --json', {
        encoding: 'utf8',
        maxBuffer: 64 * 1024 * 1024,
    });
    const byLicense: Record<string, PnpmLicenseEntry[]> = JSON.parse(raw);

    return Object.entries(byLicense)
        .flatMap(([licenseKey, entries]) =>
            entries.map((entry): CollectedPackage => {
                const licenseFile = entry.paths?.[0] ? findLicenseFile(entry.paths[0]) : null;

                return {
                    name: entry.name,
                    version: entry.versions?.[0] ?? '',
                    license: entry.license?.trim() || licenseKey,
                    author: normalizeAuthor(entry.author),
                    homepage: entry.homepage?.trim() || undefined,
                    text: licenseFile ? normalizeText(fs.readFileSync(licenseFile, 'utf8')) : null,
                };
            }),
        )
        .sort((a, b) => a.name.localeCompare(b.name));
};

const collect = (): CollectedPackage[] => {
    const packages: CollectedPackage[] = [];

    // The project itself first, so it heads the list instead of being sorted in
    // among the dependencies.
    if (fs.existsSync(PROJECT_LICENSE_FILE)) {
        packages.push({
            name: PROJECT_NAME,
            version: '',
            license: PROJECT_LICENSE,
            text: normalizeText(fs.readFileSync(PROJECT_LICENSE_FILE, 'utf8')),
        });
    }

    packages.push(...collectFromPnpm());
    return packages;
};

/**
 * Assigns a `t<n>` id per distinct license text, in first-seen order.
 *
 * Ids are positional so they stay stable as long as the sorted package list is
 * stable; the text itself is too long to use as a key.
 */
const buildTexts = (packages: CollectedPackage[]) => {
    const idsByText = new Map<string, string>();
    const texts: { id: string; license: string; text: string }[] = [];

    packages.forEach((pkg) => {
        if (!pkg.text || idsByText.has(pkg.text)) {
            return;
        }

        const id = `t${texts.length}`;
        idsByText.set(pkg.text, id);
        texts.push({ id, license: pkg.license, text: pkg.text });
    });

    return { idsByText, texts };
};

const quote = (value: string): string => JSON.stringify(value);

const render = (
    packages: CollectedPackage[],
    texts: ReturnType<typeof buildTexts>['texts'],
    idsByText: Map<string, string>,
) => {
    const optional = (key: string, value: string | undefined): string[] =>
        value ? [`        ${key}: ${quote(value)},`] : [];

    const packageLines = packages.flatMap((pkg) => [
        '    {',
        `        name: ${quote(pkg.name)},`,
        `        version: ${quote(pkg.version)},`,
        `        license: ${quote(pkg.license)},`,
        ...optional('author', pkg.author),
        ...optional('homepage', pkg.homepage),
        `        textId: ${pkg.text ? quote(idsByText.get(pkg.text)!) : 'null'},`,
        '    },',
    ]);

    const textLines = texts.flatMap((entry) => [
        '    {',
        `        id: ${quote(entry.id)},`,
        `        license: ${quote(entry.license)},`,
        `        text: ${quote(entry.text)},`,
        '    },',
    ]);

    return `/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// GENERATED FILE - DO NOT EDIT
//
// Regenerate with \`pnpm gen:licenses\` (runs as part of \`pnpm setup\`).
// Source: the project's LICENSE plus every production dependency reported by
// \`pnpm licenses list --prod --json\`.

import type { LicensePackage, LicenseText } from '@/features/settings/AboutLicenses.types.ts';

export const LICENSE_PACKAGES: LicensePackage[] = [
${packageLines.join('\n')}
];

export const LICENSE_TEXTS: LicenseText[] = [
${textLines.join('\n')}
];
`;
};

const packages = collect();
const { texts, idsByText } = buildTexts(packages);

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, render(packages, texts, idsByText));

const withoutText = packages.filter((pkg) => !pkg.text).length;
console.log(
    `licenses: ${packages.length} packages, ${texts.length} distinct texts, ${withoutText} without a license file`,
);
