name: build-alpha

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build artifacts and deploy preview
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
          fetch-depth: 0

      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version-file: './main/package.json'

      - uses: pnpm/action-setup@v4.2.0
        name: Install pnpm
        with:
          version: 11.1.2

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Build webUI
        run: |
          cd main
          pnpm ci
          pnpm build
          pnpm build-zip
          pnpm build-md5
          ls buildZip

      - name: Generate Tag Name
        id: GenTagName
        run: |
          cd main/build
          genTag="r$(git rev-list HEAD --count)"
          echo "$genTag"
          echo "value=$genTag" >> "$GITHUB_OUTPUT"

      - name: Checkout preview branch
        if: github.repository == 'Suwayomi/Suwayomi-WebUI'
        uses: actions/checkout@v4
        with:
          repository: "Suwayomi/Suwayomi-WebUI-preview"
          ref: main
          path: preview
          token: ${{ secrets.BUILD_PREVIEW_TOKEN }}

      - name: Create Tag
        if: github.repository == 'Suwayomi/Suwayomi-WebUI'
        run: |
          TAG="${{ steps.GenTagName.outputs.value }}"
          echo "tag: $TAG"
          cd preview
          echo "{ \"latest\": \"$TAG\" }" > index.json
          git add index.json
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "Updated to $TAG"
          git push origin main

          git tag $TAG
          git push origin $TAG

      - name: Upload CI Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ github.token }}
          artifacts: "main/buildZip/*"
          tag: ${{ steps.GenTagName.outputs.value }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Checkout github pages repo
        if: github.repository == 'Suwayomi/Suwayomi-WebUI'
        uses: actions/checkout@v4
        with:
          repository: "Suwayomi-WebUI-preview/suwayomi-webui-preview.github.io"
          ref: main
          path: gh-pages
          token: ${{ secrets.DEPLOY_PREVIEW_TOKEN }}

      - name: Deploy github pages
        if: github.repository == 'Suwayomi/Suwayomi-WebUI'
        run: |
          TAG="${{ steps.GenTagName.outputs.value }}"
          rm -rf gh-pages/*
          cp -r main/build/* gh-pages
          cd gh-pages
          cp index.html 404.html
          git add -A
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "$TAG"
          git push origin main
