name: Auto build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build artifacts and publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.13.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout main branch
        uses: actions/checkout@v7
        with:
          ref: main
          path: main
          fetch-depth: 0

      - name: Set up NodeJs
        uses: actions/setup-node@v7
        with:
          node-version-file: './main/package.json'

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11.1.2

      - name: Build webUI (alpha)
        run: |
          cd main
          pnpm ci
          pnpm build
          SUWAYOMI_WEBUI_CHANNEL=Alpha pnpm build-zip

      - name: Generate Tag Name
        id: GenTagName
        run: |
          cd main/build
          genTag="r$(git rev-list HEAD --count)"
          echo "value=$genTag" >> "$GITHUB_OUTPUT"

      - name: Create Tag
        run: |
          TAG="${{ steps.GenTagName.outputs.value }}"
          cd main
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag $TAG
          git push origin $TAG

      - name: Upload CI Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ github.token }}
          artifacts: "main/buildZip/*"
          tag: ${{ steps.GenTagName.outputs.value }}
          prerelease: true
