name: Release

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Channel'
        required: true
        default: alpha
        type: choice
        options:
          - alpha
          - beta
          - release

jobs:
  release:
    name: Build artifacts and publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
          fetch-depth: 0

      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version-file: './main/package.json'

      - uses: pnpm/action-setup@v4.2.0
        name: Install pnpm
        with:
          version: 11.1.2

      - name: Build webUI
        env:
          CHANNEL: ${{ inputs.channel }}
        run: |
          cd main
          pnpm ci
          pnpm build
          case "$CHANNEL" in
            beta) chan="Beta" ;;
            release) chan="Release" ;;
            *) chan="Alpha" ;;
          esac
          SUWAYOMI_WEBUI_CHANNEL="$chan" pnpm build-zip

      - name: Generate Tag Name
        id: GenTagName
        run: |
          cd main/build
          genTag="r$(git rev-list HEAD --count)"
          echo "value=$genTag" >> "$GITHUB_OUTPUT"

      - name: Create Tag
        run: |
          TAG="${{ steps.GenTagName.outputs.value }}"
          cd main
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag $TAG
          git push origin $TAG

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ github.token }}
          artifacts: "main/buildZip/*"
          tag: ${{ steps.GenTagName.outputs.value }}
          prerelease: ${{ inputs.channel != 'release' }}
